// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIMKOST.Data;

#nullable disable

namespace SIMKOST.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622130449_SinkronisasiManual")]
    partial class SinkronisasiManual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SIMKOST.Models.Kamar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Harga")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Lantai")
                        .HasColumnType("int");

                    b.Property<string>("NomorKamar")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kamar");
                });

            modelBuilder.Entity("SIMKOST.Models.Pembayaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("JumlahBayar")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SewaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalBayar")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Tanggal");

                    b.Property<DateTime?>("TanggalJatuhTempo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SewaId");

                    b.ToTable("Pembayaran");
                });

            modelBuilder.Entity("SIMKOST.Models.Penghuni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoKTP")
                        .HasColumnType("longtext");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Penghuni");
                });

            modelBuilder.Entity("SIMKOST.Models.Sewa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KamarId")
                        .HasColumnType("int");

                    b.Property<int>("PenghuniId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TanggalKeluar")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KamarId");

                    b.HasIndex("PenghuniId");

                    b.ToTable("Sewa");
                });

            modelBuilder.Entity("SIMKOST.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SIMKOST.Models.Pembayaran", b =>
                {
                    b.HasOne("SIMKOST.Models.Sewa", "Sewa")
                        .WithMany("Pembayaran")
                        .HasForeignKey("SewaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sewa");
                });

            modelBuilder.Entity("SIMKOST.Models.Sewa", b =>
                {
                    b.HasOne("SIMKOST.Models.Kamar", "Kamar")
                        .WithMany("Sewa")
                        .HasForeignKey("KamarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIMKOST.Models.Penghuni", "Penghuni")
                        .WithMany("Sewa")
                        .HasForeignKey("PenghuniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kamar");

                    b.Navigation("Penghuni");
                });

            modelBuilder.Entity("SIMKOST.Models.Kamar", b =>
                {
                    b.Navigation("Sewa");
                });

            modelBuilder.Entity("SIMKOST.Models.Penghuni", b =>
                {
                    b.Navigation("Sewa");
                });

            modelBuilder.Entity("SIMKOST.Models.Sewa", b =>
                {
                    b.Navigation("Pembayaran");
                });
#pragma warning restore 612, 618
        }
    }
}
